### ISSUE TITLE
Implementation of rapidhash with Python Interface via PyO3

### ISSUE THREAD

**Issue by ryan-aoi** [Nicoshev/rapidhash#12]
Thank you for the excellent work on rapidhash.
I implemented a Python interface for RapidHash using PyO3. Based on my benchmarks, RapidHash is over twice as fast as [mmh3](https://github.com/hajimes/mmh3)(and [wyhash](https://github.com/synodriver/python-wyhash)) for almost all input lengths, which is impressive.

[ryan-aoi/rapidhash](https://github.com/ryan-aoi/rapidhash)

However, when using the Python interface, the speed is only around 10x faster than hashlib.sha1. While this is still among the fastest hash functions available, I suspect the performance difference might be due to the overhead introduced by PyO3's data conversion.

**Comment by Nicoshev** [comment]
Thanks!
Just added a link within the repo's landing page.
Cheers,
Nicolas
