### ISSUE TITLE
Rust implementation

### ISSUE THREAD

**Issue by hoxxep** [Nicoshev/rapidhash#7]
Hey! I wanted to share that I've been playing with a rust implementation of rapidhash, in case it's of interest. 

https://github.com/hoxxep/rapidhash

It's still a work in progress, but the initial hash function implementation is there. Regarding licensing, would you prefer for this to also be licensed under BSD 2-Clause, or would you be happy for it to be under MIT/Apache?

Cheers,
Liam

**Comment by Nicoshev** [comment]
This is amazing! Thanks !

I've added a link within the repo's homepage.

Cheers,
Nicolas

**Comment by Nicoshev** [comment]
Forgot to say, MIT/Apache is fine as well, choose whatever license you prefer
